package alertsystemdatabase;
// Generated Dec 28, 2011 9:22:05 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import java.sql.Timestamp;
import java.util.*;
import PRMSalert.*;
import PRMSAlertState.*;

/**
 * Alert generated by hbm2java
 */
public class Alert  implements java.io.Serializable {


     private Integer alertId;
     private Userinfo userinfo;
     private Timestamp alertCreatedTime;
     private Timestamp alertTime;
     private String alertCreatedBy;
     private String alertText;
     private Integer alertSourceType;
     private String alertSourceId;
     private String alertState;
     private Byte repeating;
     private Integer repeatFrequency;
     private Byte severity;
     private Set alerthistories = new HashSet(0);
     private AlertStateContext state;
     private Hashtable errors;

    public Alert() {
    }

	
    public Alert(Userinfo userinfo, Timestamp alertCreatedTime, String alertCreatedBy, String alertText, String alertSourceId, String alertState) {
        this.userinfo = userinfo;
        this.alertCreatedTime = alertCreatedTime;
        this.alertCreatedBy = alertCreatedBy;
        this.alertText = alertText;
        this.alertSourceId = alertSourceId;
        this.alertState = alertState;
    }
    public Alert(Userinfo userinfo, Timestamp alertCreatedTime, Timestamp alertTime, String alertCreatedBy, String alertText, Integer alertSourceType, String alertSourceId, String alertState, Byte repeating, Integer repeatFrequency, Byte severity, Set alerthistories) {
       this.userinfo = userinfo;
       this.alertCreatedTime = alertCreatedTime;
       this.alertTime = alertTime;
       this.alertCreatedBy = alertCreatedBy;
       this.alertText = alertText;
       this.alertSourceType = alertSourceType;
       this.alertSourceId = alertSourceId;
       this.alertState = alertState;
       this.repeating = repeating;
       this.repeatFrequency = repeatFrequency;
       this.severity = severity;
       this.alerthistories = alerthistories;
    }
   
    public Integer getAlertId() {
        return this.alertId;
    }
    
    public void setAlertId(Integer alertId) {
        this.alertId = alertId;
    }
    public Userinfo getUserinfo() {
        return this.userinfo;
    }
    
    public void setUserinfo(Userinfo userinfo) {
        this.userinfo = userinfo;
    }
    public Timestamp getAlertCreatedTime() {
        return this.alertCreatedTime;
    }
    
    public void setAlertCreatedTime(Timestamp alertCreatedTime) {
        this.alertCreatedTime = alertCreatedTime;
    }
    public Timestamp getAlertTime() {
        return this.alertTime;
    }
    
    public void setAlertTime(Timestamp alertTime) {
        this.alertTime = alertTime;
    }
    public String getAlertCreatedBy() {
        return this.alertCreatedBy;
    }
    
    public void setAlertCreatedBy(String alertCreatedBy) {
        this.alertCreatedBy = alertCreatedBy;
    }
    public String getAlertText() {
        return this.alertText;
    }
    
    public void setAlertText(String alertText) {
        this.alertText = alertText;
    }
    public Integer getAlertSourceType() {
        return this.alertSourceType;
    }
    
    public void setAlertSourceType(Integer alertSourceType) {
        this.alertSourceType = alertSourceType;
    }
    public String getAlertSourceId() {
        return this.alertSourceId;
    }
    
    public void setAlertSourceId(String alertSourceId) {
        this.alertSourceId = alertSourceId;
    }
    public String getAlertState() {
        return this.alertState;
    }
    
    public void setAlertState(String alertState) {
        this.alertState = alertState;
    }
    public Byte getRepeating() {
        return this.repeating;
    }
    
    public void setRepeating(Byte repeating) {
        this.repeating = repeating;
    }
    public Integer getRepeatFrequency() {
        return this.repeatFrequency;
    }
    
    public void setRepeatFrequency(Integer repeatFrequency) {
        this.repeatFrequency = repeatFrequency;
    }
    public Byte getSeverity() {
        return this.severity;
    }
    
    public void setSeverity(Byte severity) {
        this.severity = severity;
    }
    public Set getAlerthistories() {
        return this.alerthistories;
    }
    
    public void setAlerthistories(Set alerthistories) {
        this.alerthistories = alerthistories;
    }

public boolean validate() {
    boolean allOk=true;
    if (alertText.equals("")) {
      errors.put("alertText","Please enter the Alert text");
      alertText="";
      allOk=false;
    }
    
    if (repeatFrequency > 6 & repeatFrequency < 0 ) {
      errors.put("repeatFrequency","Please enter a repeat Frequency");
      repeatFrequency=0;
      allOk=false;
    }
    if (severity > 5 & severity < 0) {
      errors.put("severity","Please enter the Alert Severity");
      severity=0;
      allOk=false;
    }
    if (alertCreatedBy.equals("")) {
      errors.put("alertSetBy","Please enetr the Alert Set By");
      alertCreatedBy="";
      allOk=false;
    }
        return allOk;
  }
  public String getErrorMsg(String s) {
    String errorMsg =(String)errors.get(s.trim());
    return (errorMsg == null) ? "":errorMsg;
  }
  
  public void setAlert()
  {
      state = new AlertStateContext();
      SetAlertController setAlertController = new SetAlertController(this);
      setAlertController.setAlert();
      state.alertSet(this);
  }
  
  public void view()
  {
    state.alertDisplayed(this);  
  }
  
  public void setState()
  {
      state.alertSet(this);
  }
  
  public void delete()
  {
      state.Alertclosed(this);
  }
  
  public void snooze(Timestamp snoozeTime)
  {
      this.alertTime = snoozeTime;
      state.Alertsnoozed(this);
  }




}


