package alertsystemdatabase;
// Generated Dec 28, 2011 9:22:05 PM by Hibernate Tools 3.2.1.GA


import java.sql.Timestamp;

/**
 * Alertarchive generated by hbm2java
 */
public class Alertarchive  implements java.io.Serializable {


     private Integer alertArchiveId;
     private Integer alertId;
     private Timestamp alertCreatedTime;
     private Timestamp alertTime;
     private Timestamp alertArchivedTime;
     private String alertCreatedBy;
     private String userId;
     private String alertText;
     private Integer alertSourceType;
     private String alertSourceId;
     private String alertState;
     private Byte repeating;
     private Integer repeatFrequency;
     private Byte severity;

    public Alertarchive() {
    }

	
    public Alertarchive(Timestamp alertArchivedTime) {
        this.alertArchivedTime = alertArchivedTime;
    }
    public Alertarchive(Integer alertId, Timestamp alertCreatedTime, Timestamp alertTime, Timestamp alertArchivedTime, String alertCreatedBy, String userId, String alertText, Integer alertSourceType, String alertSourceId, String alertState, Byte repeating, Integer repeatFrequency, Byte severity) {
       this.alertId = alertId;
       this.alertCreatedTime = alertCreatedTime;
       this.alertTime = alertTime;
       this.alertArchivedTime = alertArchivedTime;
       this.alertCreatedBy = alertCreatedBy;
       this.userId = userId;
       this.alertText = alertText;
       this.alertSourceType = alertSourceType;
       this.alertSourceId = alertSourceId;
       this.alertState = alertState;
       this.repeating = repeating;
       this.repeatFrequency = repeatFrequency;
       this.severity = severity;
    }
   
    public Integer getAlertArchiveId() {
        return this.alertArchiveId;
    }
    
    public void setAlertArchiveId(Integer alertArchiveId) {
        this.alertArchiveId = alertArchiveId;
    }
    public Integer getAlertId() {
        return this.alertId;
    }
    
    public void setAlertId(Integer alertId) {
        this.alertId = alertId;
    }
    public Timestamp getAlertCreatedTime() {
        return this.alertCreatedTime;
    }
    
    public void setAlertCreatedTime(Timestamp alertCreatedTime) {
        this.alertCreatedTime = alertCreatedTime;
    }
    public Timestamp getAlertTime() {
        return this.alertTime;
    }
    
    public void setAlertTime(Timestamp alertTime) {
        this.alertTime = alertTime;
    }
    public Timestamp getAlertArchivedTime() {
        return this.alertArchivedTime;
    }
    
    public void setAlertArchivedTime(Timestamp alertArchivedTime) {
        this.alertArchivedTime = alertArchivedTime;
    }
    public String getAlertCreatedBy() {
        return this.alertCreatedBy;
    }
    
    public void setAlertCreatedBy(String alertCreatedBy) {
        this.alertCreatedBy = alertCreatedBy;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getAlertText() {
        return this.alertText;
    }
    
    public void setAlertText(String alertText) {
        this.alertText = alertText;
    }
    public Integer getAlertSourceType() {
        return this.alertSourceType;
    }
    
    public void setAlertSourceType(Integer alertSourceType) {
        this.alertSourceType = alertSourceType;
    }
    public String getAlertSourceId() {
        return this.alertSourceId;
    }
    
    public void setAlertSourceId(String alertSourceId) {
        this.alertSourceId = alertSourceId;
    }
    public String getAlertState() {
        return this.alertState;
    }
    
    public void setAlertState(String alertState) {
        this.alertState = alertState;
    }
    public Byte getRepeating() {
        return this.repeating;
    }
    
    public void setRepeating(Byte repeating) {
        this.repeating = repeating;
    }
    public Integer getRepeatFrequency() {
        return this.repeatFrequency;
    }
    
    public void setRepeatFrequency(Integer repeatFrequency) {
        this.repeatFrequency = repeatFrequency;
    }
    public Byte getSeverity() {
        return this.severity;
    }
    
    public void setSeverity(Byte severity) {
        this.severity = severity;
    }




}


