package alertsystemdatabase;
// Generated Dec 28, 2011 9:22:05 PM by Hibernate Tools 3.2.1.GA


import java.sql.Timestamp;

/**
 * Alerthistoryarchive generated by hbm2java
 */
public class Alerthistoryarchive  implements java.io.Serializable {


     private Integer alertHistoryArchiveId;
     private Integer alertHistoryId;
     private Integer alertId;
     private Timestamp alertUpdateTime;
     private String alertUpdateType;
     private String alertRemark;

    public Alerthistoryarchive() {
    }

	
    public Alerthistoryarchive(Timestamp alertUpdateTime) {
        this.alertUpdateTime = alertUpdateTime;
    }
    public Alerthistoryarchive(Integer alertHistoryId, Integer alertId, Timestamp alertUpdateTime, String alertUpdateType, String alertRemark) {
       this.alertHistoryId = alertHistoryId;
       this.alertId = alertId;
       this.alertUpdateTime = alertUpdateTime;
       this.alertUpdateType = alertUpdateType;
       this.alertRemark = alertRemark;
    }
   
    public Integer getAlertHistoryArchiveId() {
        return this.alertHistoryArchiveId;
    }
    
    public void setAlertHistoryArchiveId(Integer alertHistoryArchiveId) {
        this.alertHistoryArchiveId = alertHistoryArchiveId;
    }
    public Integer getAlertHistoryId() {
        return this.alertHistoryId;
    }
    
    public void setAlertHistoryId(Integer alertHistoryId) {
        this.alertHistoryId = alertHistoryId;
    }
    public Integer getAlertId() {
        return this.alertId;
    }
    
    public void setAlertId(Integer alertId) {
        this.alertId = alertId;
    }
    public Timestamp getAlertUpdateTime() {
        return this.alertUpdateTime;
    }
    
    public void setAlertUpdateTime(Timestamp alertUpdateTime) {
        this.alertUpdateTime = alertUpdateTime;
    }
    public String getAlertUpdateType() {
        return this.alertUpdateType;
    }
    
    public void setAlertUpdateType(String alertUpdateType) {
        this.alertUpdateType = alertUpdateType;
    }
    public String getAlertRemark() {
        return this.alertRemark;
    }
    
    public void setAlertRemark(String alertRemark) {
        this.alertRemark = alertRemark;
    }

}


