package alertsystemdatabase;
// Generated Dec 28, 2011 9:22:05 PM by Hibernate Tools 3.2.1.GA


import java.sql.Timestamp;

/**
 * Alerthistory generated by hbm2java
 */
public class Alerthistory  implements java.io.Serializable {


     private Integer alertHistoryId;
     private Alert alert;
     private Timestamp alertUpdateTime;
     private String alertUpdateType;
     private String alertRemark;

    public Alerthistory() {
    }

	
    public Alerthistory(Alert alert, Timestamp alertUpdateTime, String alertUpdateType) {
        this.alert = alert;
        this.alertUpdateTime = alertUpdateTime;
        this.alertUpdateType = alertUpdateType;
    }
    public Alerthistory(Alert alert, Timestamp alertUpdateTime, String alertUpdateType, String alertRemark) {
       this.alert = alert;
       this.alertUpdateTime = alertUpdateTime;
       this.alertUpdateType = alertUpdateType;
       this.alertRemark = alertRemark;
    }
   
    public Integer getAlertHistoryId() {
        return this.alertHistoryId;
    }
    
    public void setAlertHistoryId(Integer alertHistoryId) {
        this.alertHistoryId = alertHistoryId;
    }
    public Alert getAlert() {
        return this.alert;
    }
    
    public void setAlert(Alert alert) {
        this.alert = alert;
    }
    public Timestamp getAlertUpdateTime() {
        return this.alertUpdateTime;
    }
    
    public void setAlertUpdateTime(Timestamp alertUpdateTime) {
        this.alertUpdateTime = alertUpdateTime;
    }
    public String getAlertUpdateType() {
        return this.alertUpdateType;
    }
    
    public void setAlertUpdateType(String alertUpdateType) {
        this.alertUpdateType = alertUpdateType;
    }
    public String getAlertRemark() {
        return this.alertRemark;
    }
    
    public void setAlertRemark(String alertRemark) {
        this.alertRemark = alertRemark;
    }




}


