package alertsystemdatabase;
// Generated Dec 28, 2011 9:22:05 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Userinfo generated by hbm2java
 */
public class Userinfo  implements java.io.Serializable {


     private String userId;
     private String userName;
     private String emailId;
     private Set alerts = new HashSet(0);

    public Userinfo() {
    }

	
    public Userinfo(String userId, String userName, String emailId) {
        this.userId = userId;
        this.userName = userName;
        this.emailId = emailId;
    }
    public Userinfo(String userId, String userName, String emailId, Set alerts) {
       this.userId = userId;
       this.userName = userName;
       this.emailId = emailId;
       this.alerts = alerts;
    }
   
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public Set getAlerts() {
        return this.alerts;
    }
    
    public void setAlerts(Set alerts) {
        this.alerts = alerts;
    }




}


